# Configurator
unifik_configurator_edit:
    pattern:  /configurator/{bundleName}/{namespace}
    defaults: { _controller: "UnifikDatabaseConfigBundle:Configurator:edit" }
    options: { do_not_remove: true }