<?php

namespace Flexy\DatabaseConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestMatcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestMatcherRepository extends EntityRepository
{
    /**
     * Return secured area with associated roles
     * @return type
     */
    public function findAllWithRoles() {        
        return $this->createQueryBuilder('a')
                    ->leftJoin('a.roles', 'r')
                    ->getQuery()
                    ->getResult();
    }
}
