<?php

namespace Flexy\DatabaseConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    /**
     * Return roles with parent
     * @return type
     */
    public function findAllWithParent() {        
        return $this->createQueryBuilder('a')
                    ->leftJoin('a.parent', 'p')
                    ->getQuery()
                    ->getResult();
    }    
}
